name: "scannet"
root: "/run/determined/workdir/data/scannet/scans/scene0000_00/extract"
rgb_folder: "color_resize"
K_name: "intrinsic_color_resize.txt"
width: 256
height: 256
batch_size: 1
img_num: 4
test_length: 128
data_params: "w_${dataset.width}_h_${dataset.height}_bs_${dataset.batch_size}"