data:
  data_type: "scannet"
  root: "/run/determined/workdir/data/scannet/scans/scene0000_00/extract"
  rgb_folder: "color"
  K_name: "intrinsic_color.txt"
  width: 256
  height: 256
  batch_size: 1
  img_num: 4
  data_params: "w_${data.width}_h_${data.height}_bs_${data.batch_size}"

model:
  patch_size: 16
  max_input_images: 4
  channels: 3
  width: ${data.width}
  height: ${data.height}
  rand_input_image_embed: True
  perceptual_loss_weight: 0.5 # they use 0.5 for scene-level, 1.0 for object-level
  decoder_kwargs:
    dim: 256
    depth: 6
    heads: 8
    attn_dim_head: 64
    use_rmsnorm: True
    add_value_residual: True
    ff_glu: True
  log: ${logger.log}
  use_wandb: ${logger.use_wandb}
  lr: ${train.trainer.lr}
  model_params: "dp_${model.decoder_kwargs.depth}_dim_${model.decoder_kwargs.dim}_p_${model.patch_size}"

train:
  seed: 42
  resume: False
  ckpt: ""
  trainer:
    limit_train_batches: 200
    check_val_every_n_epoch: 100
    max_epochs: 2000
    lr: 4e-4

logger:
  log: False
  output_dir: "./outputs"
  name: "${model.model_params}_${data.data_params}_epo_${train.trainer.max_epochs}"
  use_wandb: False
  wandb:
    project: "lvsm"
    name: "${logger.name}"
